language: php

php:
  - 7.1
  - 7.2

sudo: false

services:
  - mysql

before_script:
  - mysql -e 'create database if not exists etuke;'
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - cp .env.test .env
  - php artisan key:generate

script:
  - composer test